name: CI - Build Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Astro project
      run: npm run build
      
    - name: Run Claude on failure
      if: failure() && github.event_name == 'pull_request'
      uses: anthropics/claude-code-action@beta
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        direct_prompt: |
          The CI build has failed. Please analyze the error logs from the previous steps to understand what went wrong.
          
          Steps to take:
          1. Examine the build error messages carefully
          2. Identify the root cause of the failure
          3. If you can fix the issue, make the necessary changes and commit them with a descriptive message
          4. If the issue is complex or unclear, provide a detailed comment explaining:
             - What the error indicates
             - Possible causes
             - Suggested next steps for investigation or resolution
          
          Focus on providing a clear analysis and actionable solution or guidance.
