name: CI - Build Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Astro project
      run: npm run build
      
    - name: Run Claude on failure
      if: failure() && github.event_name == 'pull_request'
      uses: anthropics/claude-code-action@beta
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        direct_prompt: |
          The CI build has failed. Please analyze the error logs from the "Build Astro project" step above and fix the build error.
          
          The error shows that the module '@astrojs/non-existent-plugin' cannot be found. Please remove this import and its usage from astro.config.mjs to fix the build.
          
          After making the fix, commit the changes with a descriptive message.